#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the closestNumbers function below.
def closestNumbers(arr):
    arr.sort()
    min=arr[1]-arr[0]
    output=[]
    for i in range(0,len(arr)-1):
        if abs(arr[i]-arr[i+1])==min:
            min=abs(arr[i]-arr[i+1])
            output.append(arr[i])
            output.append(arr[i+1])
        elif abs(arr[i]-arr[i+1])<min:
            output=[]
            min=abs(arr[i]-arr[i+1])
            output.append(arr[i])
            output.append(arr[i+1])
    return output
    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())


    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
