#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the activityNotifications function below.
def activityNotifications(expenditure, d, n):
    c=0
    a=0
    if d%2==0:
        f=1
    else:
        f=0
    if f==0:
        for i in range(d,n-1):
            arr=expenditure[c:i]
            arr.sort()
            s=arr[int(d/2)]
            if s<expenditure[i]:
                a+=1
            c+=1
    else:
        for i in range(d,n-1):
            arr=expenditure[c:i]
            arr.sort()
            s=arr[int(d/2)]+arr[int(d/2)-1]/2
            if s<expenditure[i]:
                a+=1
            c+=1
    return a


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    expenditure = list(map(int, input().rstrip().split()))

    result = activityNotifications(expenditure, d, n)

    fptr.write(str(result) + '\n')

    fptr.close()
