#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the insertionSort2 function below.
def insertionSort2(n, arr):
    for j in range(1,n):
        key=arr[j]
        i=j-1
        while(i>=0 and arr[i]>key):
            arr[i+1]=arr[i]
            i-=1
        arr[i+1]=key
        print(*arr)
        

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)
